# Generated by Django 4.2.7 on 2025-11-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userfavoritemovie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratings",
                to="movies.movie",
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["tmdb_id"], name="movies_movi_tmdb_id_0e4cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-popularity"], name="movies_movi_popular_3c541f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-vote_average"], name="movies_movi_vote_av_12ed28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfavoritemovie",
            index=models.Index(
                fields=["user", "movie"], name="movies_user_user_id_509c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfavoritemovie",
            index=models.Index(
                fields=["user", "-created_at"], name="movies_user_user_id_f49065_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfavoritemovie",
            unique_together={("user", "movie")},
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["user", "movie"], name="movies_movi_user_id_afdb33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movierating",
            index=models.Index(
                fields=["movie", "-rating"], name="movies_movi_movie_i_3fb27e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movierating",
            unique_together={("user", "movie")},
        ),
    ]
